### ISSUE TITLE
URL Auto Redirector 1.2.0

### ISSUE THREAD

**Issue by crispgm** [UrlAutoRedirector/UrlAutoRedirector#39]
- [x] Option Page interaction optimisation #36 
- [x] BaiduToGoogle defaults disabled #37 
- [x] Add Chinese font #38
